### ISSUE TITLE
help data

### ISSUE THREAD

**Issue by GlauberF** [beevelop/ng-feathers#37]
**I'm getting the date, but I can not play on my ngRepeat**

my code:

`auditoriaService.find().then(function(res) {
            console.log(res);
            vm.audit = res.data;
        })
` 

no ng-repeat I call it that:

`<ul><li ng-repeat="a in vm.audit">{{a.name}}</li></ul>`

**Comment by beevelop** [comment]
I'm just guessing here, but you might need to trigger `$scope.$apply()` in order to get the results rendered. Additionally you can prevent side-effects for the data itself, by adding `track by $index` to the ng-repeat.

**Comment by GlauberF** [comment]
sure, worked perfectly.
I am having another question on get/find `productService.find()`, how can I work with pagination?

**Comment by beevelop** [comment]
This does depend on your implementation and use data provider. Which ORM do you use in your feathers Backend?

**Comment by GlauberF** [comment]
MongoDB

**Comment by beevelop** [comment]
With Sequelize or Mongoose?

**Comment by GlauberF** [comment]
Mongoose

**Comment by beevelop** [comment]
Have a look at https://docs.feathersjs.com/api/databases/querying.html
You can use `$limit` and `$skip` to do pagination:
```js
// Retrieves the next two unread messages
app.service('messages').find({
  query: {
    $limit: 2,
    $skip: 2,
    read: false
  }
});
```

Check out their help section at https://docs.feathersjs.com/help/readme.html for general usage and examples.
