### ISSUE TITLE
requisition headers

### ISSUE THREAD

**Issue by GlauberF** [beevelop/ng-feathers#38]
when I make a find the requisition object, example the headers do not go together?

What if I want the header to be sent together, how do I do it?

**Comment by beevelop** [comment]
Sorry, I don't really get what you are trying to accomplish. Could you provide some code samples and a deeper explanation of your problem.

**Comment by GlauberF** [comment]
when you query data, through a `personService.find()` function, does this generate an HTTP call?

Why would I need to insert more data into this query in the header.

**Comment by beevelop** [comment]
Please refer to the official FeatherJs documentation (there is a chapter dealing with headers): https://docs.feathersjs.com/api/rest.html

This library is just a wrapper for the official FeatherJs Client.
