### ISSUE TITLE
Error: Timeout of 5000ms

### ISSUE THREAD

**Issue by GlauberF** [beevelop/ng-feathers#39]
my application was communicating 100% with my backend, but now this error started to appear.

![erro feat](https://user-images.githubusercontent.com/11314585/32077348-e1e0b404-ba81-11e7-9dc5-632098217456.png)

`Uncaught (in promise) Error: Timeout of 5000ms exceeded calling auditoria::find`

**Comment by beevelop** [comment]
Please refer your questions to the official FeatherJS community. This repository is still just a wrapper for the official FeatherJS client. For specific questions about your implementation, please consult with the official FeatherJS documentation or Slack chat.

**Comment by GlauberF** [comment]
in the community feathers, reported that this error is with the module and I noticed that the error happens after pressing F5.
see the open issue and answer it in the feathers repository : (https://github.com/feathersjs/feathers/issues/711#issuecomment-340003364)
