### ISSUE TITLE
path: '/ws/'

### ISSUE THREAD

**Issue by GlauberF** [beevelop/ng-feathers#40]
if I want to use this setting:

`$feathersProvider.setSocketOpts({
         path: '/ws/'
 })`

what should i set it in my backend feathersjs?
why if today I leave enabled, the error of communication with my backend.
And what will change if I do not use it?

**Comment by beevelop** [comment]
The path can be customized via Socket.io server settings: https://socket.io/docs/server-api/
It defaults to `/socket.io` and does not need to be changed. There are some scenarios in which you might want to configure your Socket options. The example in the `README` does just provide a simple use case for the `setSocketOpts()` function.
