### ISSUE TITLE
error in socket communication when pressing F5

### ISSUE THREAD

**Issue by GlauberF** [beevelop/ng-feathers#41]
**error in socket communication when pressing F5**

![erro feat](https://user-images.githubusercontent.com/11314585/32077348-e1e0b404-ba81-11e7-9dc5-632098217456.png)

`Uncaught (in promise) Error: Timeout of 5000ms exceeded calling auditoria::find`

in the community feathers, reported that this error is with the module and I noticed that the error happens after pressing F5.
see the open issue and answer it in the feathers repository : (https://github.com/feathersjs/feathers/issues/711#issuecomment-340003364)

**Comment by beevelop** [comment]
As daffl suggested:
> Try using the Feathers client directly to verify first.

Could you provide some samples of the affected code (frontend & backend implementation)? Do you use the REST or WS-Client?

**Comment by beevelop** [comment]
You might have a look at the developer console's network tab and verify it's not caused by your backend implementation. Is the backend itself reachable when you are getting the exception?

**Comment by GlauberF** [comment]
I use socketio.

my configuration on the front is:

` $feathersProvider.setEndpoint('http://IP:3000/');
  $feathersProvider.useSocket(true)`

in the backend, I use the default settings that feathers generates.

the error only happens, when in the frontend I press F5

I'm using the javascript file (ng-feathers.standalone.min.js), alone.

**Comment by beevelop** [comment]
Is you are app reachable via `http://IP:3000` in the very same moment, when trying to connect via frontend app?

**Comment by GlauberF** [comment]
yes, through angularjs $ http is working

![captura de tela de 2017-10-27 09-36-18](https://user-images.githubusercontent.com/11314585/32115972-878ba9a4-bb27-11e7-9345-ca23bf8399ac.png)

in the image, you can see that the first call worked, usso ($ http of angularjs).
on the second gave an error, I use your file

**Comment by beevelop** [comment]
No buddy. Make sure, that your backend is reachable from your browser / via curl / whatever. I just want to rule out the possibility, that the backend might be crashing right after your first request.

You could test the following scenario:
- Launch the backend
- `curl -v http://IP:3000`
- Launch the frontend and make the initial request
- Reload the frontend (and expect it to fail again)
- `curl -v http://IP:3000` again
- Post the output over here to rule out my first guess.

**Comment by GlauberF** [comment]
through the browser
![captura de tela de 2017-10-27 15-08-45](https://user-images.githubusercontent.com/11314585/32116142-2b6cd23c-bb28-11e7-8ce3-6e06fecf70e5.png)

console when error occurs
![captura de tela de 2017-10-27 15-07-13](https://user-images.githubusercontent.com/11314585/32116144-2bd894f4-bb28-11e7-9bd7-807c8029c54b.png)

I do not use this setting here:
` $feathersProvider.setSocketOpts({path: '/ws/'})`
Could that be the problem?

**Comment by beevelop** [comment]
There is no way to properly guess the origin of your problem, without providing solid information in the different states: before the problem occurs and right after the error occured. In each state you need to provide information about:
- the state of your frontend (connected / disconnected)
- the state of your backend (logs & connectivity – see curl)

**Comment by GlauberF** [comment]
![captura de tela de 2017-10-27 15-31-31](https://user-images.githubusercontent.com/11314585/32116957-5e56643a-bb2b-11e7-8c25-04d04e0cebdb.png)

**Comment by beevelop** [comment]
Please verify the functionality of your application first. If you are still struggling using ng-feathers, you should try out the official Feathers client (in order to rule out bad backend implementations). Just – and only – in the case that the problem is isolated to ng-feathers, feel free to open an issue for this exact, verified, technical bug (this is not the right place to provide guided debugging / general coding guidance).
