### ISSUE TITLE
Data Fetching not visible in angularjs expression

### ISSUE THREAD

**Issue by imshibaji** [beevelop/ng-feathers#44]
var messages = $feathers.service('messages');

    messages.find().then(function(results){
        $scope.msgs = results.data; // This line not working
        console.log(results.data); // This line works
        return results.data;
    });

**Comment by beevelop** [comment]
What happens if you explicitly trigger $apply:
```
$scope.$apply()
```

**Comment by beevelop** [comment]
@imshibaji Did you have a chance to test if the `$apply()` works?

**Comment by imshibaji** [comment]
Yes, It's work. Thank you @beevelop

**Comment by beevelop** [comment]
Awesome. Thank you for verifying.
